### ISSUE TITLE
demo有问题吧

### ISSUE THREAD

**Issue by luboq** [panteng/ie-blocker#1]
http://panteng.me/demos/ie-blocker/demo.zhCN.html
IE8下，并无提示。

**Comment by panteng** [comment]
我在虚拟机（Win7x64 IE8）下测试，是有提示的。看截图：
![qq 20160229101119](https://cloud.githubusercontent.com/assets/8369690/13384060/d77a3694-decc-11e5-9931-2c10661b4efd.png)

你的IE8的控制台中有报错吗？

**Comment by luboq** [comment]
为何要开一次F12，才能正常……

![gif](http://ww3.sinaimg.cn/large/d80a8e60gw1f1g0oh7hdlg20nf0fpqrh.gif)

**Comment by panteng** [comment]
发现原因了。
原来代码中有句console.log()语句，发布的时候忘记删除了。
IE 8浏览器在未开启F12控制台时，console是不存在，所以代码报错了。
麻烦你清空IE8缓存后再试一次。应该已经可以了。
感谢反馈~

**Comment by luboq** [comment]
:smile:
