### ISSUE TITLE
IE 11 got this blocker

### ISSUE THREAD

**Issue by CoxHong** [panteng/ie-blocker#2]
![image](https://cloud.githubusercontent.com/assets/7506530/20331493/a1cb267a-abe0-11e6-8413-012542a1606f.png)

**Comment by panteng** [comment]
Did you use conditional comment like i said in the README.md?

**Comment by CoxHong** [comment]
http://panteng.me/demos/ie-blocker/demo.zhCN.html

**Comment by CoxHong** [comment]
open your test url in ie 11: http://panteng.me/demos/ie-blocker/demo.zhCN.html

**Comment by panteng** [comment]
The demo works fine on ie11 in [Browser Sandbox](https://turbo.net/browsers). The modal didn't show up. Please check your browser.
